### ISSUE TITLE
help me fix this

### ISSUE THREAD

**Issue by KYKY62** [KYKY62/CyberNinja.github.io#1]

**Comment by raji2004** [comment]
i would love to be assigned this issue and also be told what i am meant to fix?

**Comment by KYKY62** [comment]
Just make the desktop appear more tidy and clean. thanks

**Comment by raji2004** [comment]
aiit

**Comment by raji2004** [comment]
Please don't forget to add the tag accepted

**Comment by KYKY62** [comment]
okayy
